# Generated by Django 3.0 on 2020-01-04 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='building', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Image')),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to='videos/', verbose_name='Video')),
                ('audio', models.FileField(blank=True, default=None, null=True, upload_to='audio/', verbose_name='Audio')),
                ('camera_address', models.CharField(default='', max_length=50, null=True)),
                ('old_address', models.CharField(default='', max_length=50, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('heading', models.FloatField(blank=True, default=None, null=True)),
                ('pitch', models.FloatField(blank=True, null=True)),
                ('zoom', models.FloatField(blank=True, default=None, null=True)),
                ('dateofmemory', models.DateField()),
                ('category', models.ManyToManyField(blank=True, null=True, to='memories.MemoryCategory')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
