# Generated by Django 3.0 on 2019-12-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='heading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='pitch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
