# Generated by Django 3.0 on 2020-01-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='dateofmemory',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
