# Generated by Django 3.0 on 2019-12-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20191210_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
