# Generated by Django 3.0 on 2020-01-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20200106_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='title',
            field=models.CharField(default='Another echo in time', max_length=50),
        ),
    ]
