# Generated by Django 3.0 on 2019-12-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_auto_20191223_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='audio',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audio/', verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='memory',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='videos/', verbose_name='Video'),
        ),
    ]
