# Generated by Django 3.0 on 2019-12-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_auto_20191223_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='memorycategory',
            name='category',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
