# Generated by Django 3.0 on 2020-01-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0006_auto_20191224_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='address',
            new_name='current_address',
        ),
    ]
