# Generated by Django 3.0 on 2020-01-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0007_auto_20200104_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='old_address',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
